// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: Lexer.flex

package model.scanner;

@SuppressWarnings("fallthrough")
public class Lexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\36\u0200\1\u0300\267\u0200\10\u0400\37\u0200\1\u0500"+
    "\u1000\u0200";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\1"+
    "\1\6\1\7\1\10\1\0\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\11\25\1\26\1\27\1\30\1\31\1\32\2\0\3\33"+
    "\1\34\21\33\1\35\4\33\1\36\1\37\1\40\1\41"+
    "\1\33\1\0\1\42\1\43\1\44\1\45\1\46\1\47"+
    "\1\50\1\51\1\52\1\33\1\53\1\54\1\55\1\56"+
    "\1\57\1\60\1\33\1\61\1\62\1\63\1\64\1\33"+
    "\1\65\1\66\2\33\1\67\1\70\1\71\1\72\6\0"+
    "\1\3\33\0\1\33\7\0\1\33\3\0\1\33\3\0"+
    "\1\33\1\0\1\33\6\0\1\33\1\0\1\33\6\0"+
    "\1\33\217\0\1\33\15\0\1\33\u01b6\0\1\33\3\0"+
    "\1\33\13\0\2\3\6\0\1\33\317\0\u0100\3\375\0"+
    "\1\33\2\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1536];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\1\1\2\1\4\1\5"+
    "\1\1\1\6\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\2\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\1\1\26\1\27\14\24\1\30\1\31\1\32"+
    "\1\33\1\34\1\0\1\35\3\0\1\16\2\0\1\36"+
    "\1\37\1\0\1\40\1\41\1\42\2\0\10\24\1\43"+
    "\1\24\1\44\1\45\16\24\1\0\1\46\2\0\3\24"+
    "\1\47\1\50\1\51\5\24\1\52\1\53\1\54\2\24"+
    "\1\55\6\24\1\56\1\57\1\24\1\60\2\24\2\0"+
    "\1\61\2\24\1\62\1\24\1\63\1\64\2\24\1\65"+
    "\1\24\1\66\1\67\4\24\1\70\1\24\1\71\1\72"+
    "\1\24\2\0\1\73\2\24\1\74\1\75\2\24\1\76"+
    "\1\77\1\100\2\24\1\101\2\0\2\24\1\102\1\24"+
    "\1\103\1\104\2\0\1\24\1\105\1\24\2\0\1\106"+
    "\1\24\2\0\1\24\2\0\1\24\2\0\1\24\2\0"+
    "\1\24\2\0\1\107\24\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[213];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\73\0\73\0\166\0\261\0\354\0\u0127\0\73"+
    "\0\73\0\u0162\0\73\0\73\0\73\0\73\0\73\0\u019d"+
    "\0\73\0\73\0\u01d8\0\u0213\0\73\0\73\0\u024e\0\u0289"+
    "\0\u02c4\0\u02ff\0\73\0\u033a\0\73\0\73\0\u0375\0\u03b0"+
    "\0\u03eb\0\u0426\0\u0461\0\u049c\0\u04d7\0\u0512\0\u054d\0\u0588"+
    "\0\u05c3\0\u05fe\0\73\0\73\0\73\0\73\0\73\0\354"+
    "\0\73\0\u0639\0\u0162\0\u0674\0\u06af\0\u06ea\0\u0725\0\u0760"+
    "\0\u079b\0\u07d6\0\73\0\73\0\73\0\u0811\0\u084c\0\u0887"+
    "\0\u08c2\0\u08fd\0\u0938\0\u0973\0\u09ae\0\u09e9\0\u0a24\0\u02ff"+
    "\0\u0a5f\0\u02ff\0\u0a9a\0\u0ad5\0\u0b10\0\u0b4b\0\u0b86\0\u0bc1"+
    "\0\u0bfc\0\u0c37\0\u0c72\0\u0cad\0\u0ce8\0\u0d23\0\u0d5e\0\u0d99"+
    "\0\u0dd4\0\u0e0f\0\u0725\0\u0e4a\0\u0e85\0\u0ec0\0\u0efb\0\u0f36"+
    "\0\u0f71\0\u02ff\0\u02ff\0\u0fac\0\u0fe7\0\u1022\0\u105d\0\u1098"+
    "\0\u02ff\0\u02ff\0\u02ff\0\u10d3\0\u110e\0\u02ff\0\u1149\0\u1184"+
    "\0\u11bf\0\u11fa\0\u1235\0\u1270\0\u02ff\0\u12ab\0\u12e6\0\u1321"+
    "\0\u135c\0\u1397\0\u13d2\0\u140d\0\u02ff\0\u1448\0\u1483\0\u02ff"+
    "\0\u14be\0\u02ff\0\u02ff\0\u14f9\0\u1534\0\u02ff\0\u156f\0\u15aa"+
    "\0\u02ff\0\u15e5\0\u1620\0\u165b\0\u1696\0\u02ff\0\u16d1\0\u02ff"+
    "\0\u02ff\0\u170c\0\u1747\0\u1782\0\u02ff\0\u17bd\0\u17f8\0\u02ff"+
    "\0\u02ff\0\u1833\0\u186e\0\u02ff\0\u02ff\0\u02ff\0\u18a9\0\u18e4"+
    "\0\u02ff\0\u191f\0\u195a\0\u1995\0\u19d0\0\u02ff\0\u1a0b\0\u02ff"+
    "\0\u02ff\0\u1a46\0\u1a81\0\u1abc\0\u02ff\0\u1af7\0\u1b32\0\u1b6d"+
    "\0\u02ff\0\u1ba8\0\u1be3\0\u1c1e\0\u1c59\0\u1c94\0\u1ccf\0\u1d0a"+
    "\0\u1d45\0\u1d80\0\u1dbb\0\u1df6\0\u1e31\0\u1e6c\0\u1ea7\0\u1ee2"+
    "\0\u02ff\0\u1f1d\0\u1f58\0\u1f93\0\u1fce\0\u2009\0\u2044\0\u207f"+
    "\0\u20ba\0\u20f5\0\u2130\0\u216b\0\u21a6\0\u21e1\0\u221c\0\u2257"+
    "\0\u2292\0\u22cd\0\u2308\0\u2343\0\u237e";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[213];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\3\32\1\33\1\34\1\35\1\36\1\32"+
    "\1\37\1\40\1\32\1\41\1\42\2\32\1\43\2\32"+
    "\1\44\1\45\1\32\1\46\1\47\1\50\1\51\1\32"+
    "\1\52\1\32\1\53\1\54\1\55\1\56\75\0\1\3"+
    "\121\0\1\57\41\0\7\60\1\61\27\60\1\62\33\60"+
    "\2\7\1\3\2\7\1\4\65\7\13\63\1\61\23\63"+
    "\1\64\33\63\24\0\1\65\1\24\66\0\1\66\1\67"+
    "\1\0\2\70\5\0\3\71\4\0\25\71\25\0\1\72"+
    "\1\67\1\0\2\24\5\0\3\71\4\0\25\71\35\0"+
    "\1\73\72\0\1\74\72\0\1\75\65\0\2\32\5\0"+
    "\3\32\4\0\25\32\13\0\1\76\3\0\1\77\103\0"+
    "\2\32\5\0\3\32\4\0\15\32\1\100\1\32\1\101"+
    "\5\32\30\0\2\32\5\0\3\32\4\0\15\32\1\102"+
    "\2\32\1\103\4\32\30\0\2\32\5\0\3\32\4\0"+
    "\5\32\1\104\4\32\1\105\12\32\30\0\2\32\5\0"+
    "\3\32\4\0\1\106\11\32\1\107\1\32\1\110\1\111"+
    "\7\32\30\0\2\32\5\0\3\32\4\0\5\32\1\112"+
    "\6\32\1\113\10\32\30\0\2\32\5\0\3\32\4\0"+
    "\1\114\3\32\1\115\3\32\1\116\4\32\1\117\7\32"+
    "\30\0\2\32\5\0\3\32\4\0\22\32\1\120\2\32"+
    "\30\0\2\32\5\0\3\32\4\0\17\32\1\121\5\32"+
    "\30\0\2\32\5\0\3\32\4\0\1\122\3\32\1\123"+
    "\20\32\30\0\2\32\5\0\3\32\4\0\4\32\1\124"+
    "\3\32\1\125\10\32\1\126\3\32\30\0\2\32\5\0"+
    "\3\32\4\0\1\127\16\32\1\130\5\32\30\0\2\32"+
    "\5\0\3\32\4\0\7\32\1\131\15\32\4\0\2\60"+
    "\4\0\65\60\2\63\4\0\65\63\21\0\1\72\1\67"+
    "\1\0\2\132\5\0\3\71\4\0\25\71\30\0\2\70"+
    "\71\0\2\133\66\0\1\66\2\0\2\70\5\0\3\71"+
    "\4\0\25\71\30\0\2\71\5\0\3\71\4\0\25\71"+
    "\30\0\2\132\104\0\1\134\72\0\1\135\57\0\2\32"+
    "\5\0\3\32\4\0\15\32\1\136\7\32\30\0\2\32"+
    "\5\0\3\32\4\0\4\32\1\137\20\32\30\0\2\32"+
    "\5\0\3\32\4\0\14\32\1\140\3\32\1\141\1\142"+
    "\3\32\30\0\2\32\5\0\3\32\4\0\2\32\1\143"+
    "\22\32\30\0\2\32\5\0\3\32\4\0\4\32\1\144"+
    "\20\32\30\0\2\32\5\0\3\32\4\0\10\32\1\145"+
    "\7\32\1\146\4\32\30\0\2\32\5\0\3\32\4\0"+
    "\12\32\1\147\12\32\30\0\2\32\5\0\3\32\4\0"+
    "\15\32\1\150\7\32\30\0\2\32\5\0\3\32\4\0"+
    "\17\32\1\151\5\32\30\0\2\32\5\0\3\32\4\0"+
    "\21\32\1\152\3\32\30\0\2\32\5\0\3\32\4\0"+
    "\24\32\1\153\30\0\2\32\5\0\3\32\4\0\1\154"+
    "\2\32\1\155\21\32\30\0\2\32\5\0\3\32\4\0"+
    "\14\32\1\156\10\32\30\0\2\32\5\0\3\32\4\0"+
    "\3\32\1\157\21\32\30\0\2\32\5\0\3\32\4\0"+
    "\12\32\1\160\12\32\30\0\2\32\5\0\3\32\4\0"+
    "\10\32\1\161\14\32\30\0\2\32\5\0\3\32\4\0"+
    "\2\32\1\162\11\32\1\163\10\32\30\0\2\32\5\0"+
    "\3\32\4\0\21\32\1\164\3\32\30\0\2\32\5\0"+
    "\3\32\4\0\2\32\1\165\22\32\30\0\2\32\5\0"+
    "\3\32\4\0\14\32\1\166\10\32\30\0\2\32\5\0"+
    "\3\32\4\0\17\32\1\167\5\32\30\0\2\32\5\0"+
    "\3\32\4\0\14\32\1\170\10\32\30\0\2\32\5\0"+
    "\3\32\4\0\22\32\1\171\2\32\30\0\2\32\5\0"+
    "\3\32\4\0\10\32\1\172\14\32\25\0\1\72\2\0"+
    "\2\132\5\0\3\71\4\0\25\71\13\0\1\173\76\0"+
    "\1\174\103\0\2\32\5\0\3\32\4\0\12\32\1\175"+
    "\12\32\30\0\2\32\5\0\3\32\4\0\1\176\24\32"+
    "\30\0\2\32\5\0\3\32\4\0\21\32\1\177\3\32"+
    "\30\0\2\32\5\0\3\32\4\0\7\32\1\200\15\32"+
    "\30\0\2\32\5\0\3\32\4\0\2\32\1\201\22\32"+
    "\30\0\2\32\5\0\3\32\4\0\5\32\1\202\17\32"+
    "\30\0\2\32\5\0\3\32\4\0\4\32\1\203\20\32"+
    "\30\0\2\32\5\0\3\32\4\0\20\32\1\204\4\32"+
    "\30\0\2\32\5\0\3\32\4\0\1\205\24\32\30\0"+
    "\2\32\5\0\3\32\4\0\14\32\1\206\10\32\30\0"+
    "\2\32\5\0\3\32\4\0\10\32\1\207\14\32\30\0"+
    "\2\32\5\0\3\32\4\0\4\32\1\210\20\32\30\0"+
    "\2\32\5\0\3\32\4\0\12\32\1\211\12\32\30\0"+
    "\2\32\5\0\3\32\4\0\14\32\1\212\10\32\30\0"+
    "\2\32\5\0\3\32\4\0\7\32\1\213\15\32\30\0"+
    "\2\32\5\0\3\32\4\0\6\32\1\214\16\32\30\0"+
    "\2\32\5\0\3\32\4\0\22\32\1\215\2\32\30\0"+
    "\2\32\5\0\3\32\4\0\7\32\1\216\15\32\30\0"+
    "\2\32\5\0\3\32\4\0\10\32\1\217\14\32\30\0"+
    "\2\32\5\0\3\32\4\0\7\32\1\220\15\32\30\0"+
    "\2\32\5\0\3\32\4\0\4\32\1\221\20\32\30\0"+
    "\2\32\5\0\3\32\4\0\12\32\1\222\12\32\43\0"+
    "\1\223\72\0\1\224\57\0\2\32\5\0\3\32\4\0"+
    "\11\32\1\225\13\32\30\0\2\32\5\0\3\32\4\0"+
    "\10\32\1\226\14\32\30\0\2\32\5\0\3\32\4\0"+
    "\21\32\1\227\3\32\30\0\2\32\5\0\3\32\4\0"+
    "\4\32\1\230\20\32\30\0\2\32\5\0\3\32\4\0"+
    "\21\32\1\231\3\32\30\0\2\32\5\0\3\32\4\0"+
    "\1\232\24\32\30\0\2\32\5\0\3\32\4\0\12\32"+
    "\1\233\12\32\30\0\2\32\5\0\3\32\4\0\21\32"+
    "\1\234\3\32\30\0\2\32\5\0\3\32\4\0\1\235"+
    "\24\32\30\0\2\32\5\0\3\32\4\0\4\32\1\236"+
    "\20\32\30\0\2\32\5\0\3\32\4\0\17\32\1\237"+
    "\5\32\30\0\2\32\5\0\3\32\4\0\14\32\1\240"+
    "\10\32\30\0\2\32\5\0\3\32\4\0\4\32\1\241"+
    "\20\32\13\0\1\242\76\0\1\243\103\0\2\32\5\0"+
    "\3\32\4\0\14\32\1\244\10\32\30\0\2\32\5\0"+
    "\3\32\4\0\15\32\1\245\7\32\30\0\2\32\5\0"+
    "\3\32\4\0\14\32\1\246\10\32\30\0\2\32\5\0"+
    "\3\32\4\0\15\32\1\247\7\32\30\0\2\32\5\0"+
    "\3\32\4\0\14\32\1\250\10\32\30\0\2\32\5\0"+
    "\3\32\4\0\6\32\1\251\16\32\20\0\1\252\72\0"+
    "\1\253\102\0\2\32\5\0\3\32\4\0\22\32\1\254"+
    "\2\32\30\0\2\32\5\0\3\32\4\0\20\32\1\255"+
    "\4\32\30\0\2\32\5\0\1\32\1\256\1\32\4\0"+
    "\25\32\43\0\1\257\72\0\1\260\57\0\2\32\5\0"+
    "\3\32\4\0\4\32\1\261\20\32\30\0\2\32\5\0"+
    "\3\32\4\0\15\32\1\262\7\32\43\0\1\263\72\0"+
    "\1\264\57\0\2\32\5\0\3\32\4\0\20\32\1\265"+
    "\4\32\26\0\1\266\72\0\1\267\74\0\2\32\5\0"+
    "\2\32\1\270\4\0\25\32\74\0\1\271\72\0\1\272"+
    "\26\0\2\32\5\0\3\32\4\0\10\32\1\273\14\32"+
    "\42\0\1\274\72\0\1\275\60\0\2\32\5\0\3\32"+
    "\4\0\1\276\24\32\45\0\1\277\72\0\1\300\55\0"+
    "\2\32\5\0\3\32\4\0\20\32\1\301\4\32\43\0"+
    "\1\302\72\0\1\303\72\0\1\304\72\0\1\305\73\0"+
    "\1\306\72\0\1\307\47\0\1\310\72\0\1\311\73\0"+
    "\1\312\72\0\1\313\113\0\1\314\72\0\1\315\42\0"+
    "\1\316\76\0\1\317\116\0\1\320\72\0\1\321\42\0"+
    "\1\322\76\0\1\323\116\0\1\324\72\0\1\325\42\0"+
    "\1\3\76\0\1\3\57\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[9145];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\4\1\2\11\1\1\5\11\1\1\2\11"+
    "\2\1\2\11\4\1\1\11\1\1\2\11\14\1\5\11"+
    "\1\0\1\11\3\0\1\1\2\0\2\1\1\0\3\11"+
    "\2\0\32\1\1\0\1\1\2\0\35\1\2\0\26\1"+
    "\2\0\15\1\2\0\6\1\2\0\3\1\2\0\2\1"+
    "\2\0\1\1\2\0\1\1\2\0\1\1\2\0\1\1"+
    "\2\0\1\1\24\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[213];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    /*Estos son los lexemas, se implementan en otro orden por eso las listas de aqui abajo
    solo sirven para tener una idea de los lexemas que se pueden encontrar en el código*/
    // String[] palabrasReservadas_RW = {"if", "else", "while", "for", "return", "break", "continue", "fn", "bool", "int", "float", "string", "true", "false", "null"};
    // String[] palabrasReservadas_RW_Extra = {"mean", "max", "min", "median", "mode"};
    // String[] identificadores_ID = {"Nombres de variables", "funciones", "procedimientos", "tipos de datos"};
    // String[] operadoresAritmeticos_OP_AR = {"+", "-", "*", "/", "%"};
    // String[] operadoresRelacionales_OP_REL = {"<", "<=", ">", ">=", "==", "!="};
    // String[] operadoresLogicos_OP_LOG = {"&&", "||", "!"};
    // String[] operadorAsignacion_OP_ASIGN = {"="};
    // String[] delimitadoresParentesis_DEL_LR = {"(", ")", "[", "]", "{", "}"};
    // String[] delimitadoresComillasComentarios_COM = {"\"", "'"};
    // String[] delimitadoresPuntuacion_DEL_PUNT = {";", ",", ".", ":"};
    // String[] literalesNumericos = {"MAX_INT", "MAX_FLOAT"};
    // String[] literalesCadena = {"\"\"", "'C'"};
    // String[] literalesBooleanos_LIT_BOOL = {"true", "false"};
    // String[] comentarios = {"Se utilizan para documentar el código y no son interpretados por el compilador. comienzan con #"};

    // String[] ALL_TOKENS = ['IF', 'ELSE', 'ELIF', 'WHILE', 'FOR', 'RETURN', 'BREAK', 'CONTINUE', 'FN', 'BOOL', 'INT', 'FLOAT', 'STRING', 'TRUE', 'FALSE', 'NULL', 'MEAN', 'MAX', 'MIN', 'MEDIAN', 'MODE', 'OP_SUMA', 'OP_RESTA', 'OP_MULT', 'OP_DIV', 'OP_MOD', 'OP_MENOR', 'OP_MENOR_IGUAL', 'OP_MAYOR', 'OP_MAYOR_IGUAL', 'OP_IGUAL', 'OP_DIFERENTE', 'OP_AND', 'OP_OR', 'OP_NOT', 'OP_ASIGN', 'L_PARENTESIS', 'R_PARENTESIS', 'L_LLAVE', 'R_LLAVE', 'L_CORCHETE', 'R_CORCHETE', 'COMA', 'PUNTO_COMA', 'PUNTO', 'DOS_PUNTOS', 'NUM_ENTERO', 'NUM_FLOTANTE', 'STRING', 'E_NUM_START_ZERO', 'E_ID_NO_', 'E_SIMB_NOT_FOUND']

    /* Explicación: se usa un enum de java que "enumera" cada nombre con un numero, esto se hace porque aun no se puede usar Symbol y Token de java_cup.runtime porque se necesita un archivo CUP y aun no se puede usar la libreria CUP porque hace parte del taller 2 y el profe prohibió eso, asi que en taller 1 --> enum */
    
    private Token token(TokenType type, String lexeme, int line, int column){
        return new Token(type, lexeme, line, column);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
              {
                return new Token(TokenType.EOF, "", yyline, yycolumn);
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return token(TokenType.E_SIMB_NOT_FOUND, yytext(), yyline, yycolumn);
            }
          // fall through
          case 72: break;
          case 2:
            { /*Ignorar*/
            }
          // fall through
          case 73: break;
          case 3:
            { return token(TokenType.OP_NOT, yytext(), yyline, yycolumn);
            }
          // fall through
          case 74: break;
          case 4:
            { return token(TokenType.OP_MOD, yytext(), yyline, yycolumn);
            }
          // fall through
          case 75: break;
          case 5:
            { return token(TokenType.OP_AND, yytext(), yyline, yycolumn);
            }
          // fall through
          case 76: break;
          case 6:
            { return token(TokenType.L_PARENTESIS, yytext(), yyline, yycolumn);
            }
          // fall through
          case 77: break;
          case 7:
            { return token(TokenType.R_PARENTESIS, yytext(), yyline, yycolumn);
            }
          // fall through
          case 78: break;
          case 8:
            { return token(TokenType.OP_MULT, yytext(), yyline, yycolumn);
            }
          // fall through
          case 79: break;
          case 9:
            { return token(TokenType.OP_SUMA, yytext(), yyline, yycolumn);
            }
          // fall through
          case 80: break;
          case 10:
            { return token(TokenType.COMA, yytext(), yyline, yycolumn);
            }
          // fall through
          case 81: break;
          case 11:
            { return token(TokenType.OP_RESTA, yytext(), yyline, yycolumn);
            }
          // fall through
          case 82: break;
          case 12:
            { return token(TokenType.PUNTO, yytext(), yyline, yycolumn);
            }
          // fall through
          case 83: break;
          case 13:
            { return token(TokenType.OP_DIV, yytext(), yyline, yycolumn);
            }
          // fall through
          case 84: break;
          case 14:
            { return token(TokenType.LIT_INT, yytext(), yyline, yycolumn);
            }
          // fall through
          case 85: break;
          case 15:
            { return token(TokenType.DOS_PUNTOS, yytext(), yyline, yycolumn);
            }
          // fall through
          case 86: break;
          case 16:
            { return token(TokenType.PUNTO_COMA, yytext(), yyline, yycolumn);
            }
          // fall through
          case 87: break;
          case 17:
            { return token(TokenType.OP_MENOR, yytext(), yyline, yycolumn);
            }
          // fall through
          case 88: break;
          case 18:
            { return token(TokenType.OP_ASIGN, yytext(), yyline, yycolumn);
            }
          // fall through
          case 89: break;
          case 19:
            { return token(TokenType.OP_MAYOR, yytext(), yyline, yycolumn);
            }
          // fall through
          case 90: break;
          case 20:
            { return token(TokenType.IDENTIFICADOR, yytext(), yyline, yycolumn);
            }
          // fall through
          case 91: break;
          case 21:
            { return token(TokenType.L_CORCHETE, yytext(), yyline, yycolumn);
            }
          // fall through
          case 92: break;
          case 22:
            { return token(TokenType.R_CORCHETE, yytext(), yyline, yycolumn);
            }
          // fall through
          case 93: break;
          case 23:
            { return token(TokenType.OP_POT, yytext(), yyline, yycolumn);
            }
          // fall through
          case 94: break;
          case 24:
            { return token(TokenType.L_LLAVE, yytext(), yyline, yycolumn);
            }
          // fall through
          case 95: break;
          case 25:
            { return token(TokenType.OP_OR, yytext(), yyline, yycolumn);
            }
          // fall through
          case 96: break;
          case 26:
            { return token(TokenType.R_LLAVE, yytext(), yyline, yycolumn);
            }
          // fall through
          case 97: break;
          case 27:
            { return token(TokenType.OP_MCTMZ, yytext(), yyline, yycolumn);
            }
          // fall through
          case 98: break;
          case 28:
            { return token(TokenType.OP_DIFERENTE, yytext(), yyline, yycolumn);
            }
          // fall through
          case 99: break;
          case 29:
            { return token(TokenType.LIT_STRING, yytext(), yyline, yycolumn);
            }
          // fall through
          case 100: break;
          case 30:
            { return token(TokenType.E_NUM_START_ZERO, yytext(), yyline, yycolumn);
            }
          // fall through
          case 101: break;
          case 31:
            { return token(TokenType.E_ID_START_DIGIT, yytext(), yyline, yycolumn);
            }
          // fall through
          case 102: break;
          case 32:
            { return token(TokenType.OP_MENOR_IGUAL, yytext(), yyline, yycolumn);
            }
          // fall through
          case 103: break;
          case 33:
            { return token(TokenType.OP_IGUAL, yytext(), yyline, yycolumn);
            }
          // fall through
          case 104: break;
          case 34:
            { return token(TokenType.OP_MAYOR_IGUAL, yytext(), yyline, yycolumn);
            }
          // fall through
          case 105: break;
          case 35:
            { return token(TokenType.FN, yytext(), yyline, yycolumn);
            }
          // fall through
          case 106: break;
          case 36:
            { return token(TokenType.IF, yytext(), yyline, yycolumn);
            }
          // fall through
          case 107: break;
          case 37:
            { return token(TokenType.IN, yytext(), yyline, yycolumn);
            }
          // fall through
          case 108: break;
          case 38:
            { return token(TokenType.LIT_FLOAT, yytext(), yyline, yycolumn);
            }
          // fall through
          case 109: break;
          case 39:
            { return token(TokenType.COS, yytext(), yyline, yycolumn);
            }
          // fall through
          case 110: break;
          case 40:
            { return token(TokenType.COT, yytext(), yyline, yycolumn);
            }
          // fall through
          case 111: break;
          case 41:
            { return token(TokenType.CSC, yytext(), yyline, yycolumn);
            }
          // fall through
          case 112: break;
          case 42:
            { return token(TokenType.FOR, yytext(), yyline, yycolumn);
            }
          // fall through
          case 113: break;
          case 43:
            { return token(TokenType.INT, yytext(), yyline, yycolumn);
            }
          // fall through
          case 114: break;
          case 44:
            { return token(TokenType.MAX, yytext(), yyline, yycolumn);
            }
          // fall through
          case 115: break;
          case 45:
            { return token(TokenType.MIN, yytext(), yyline, yycolumn);
            }
          // fall through
          case 116: break;
          case 46:
            { return token(TokenType.SEC, yytext(), yyline, yycolumn);
            }
          // fall through
          case 117: break;
          case 47:
            { return token(TokenType.SIN, yytext(), yyline, yycolumn);
            }
          // fall through
          case 118: break;
          case 48:
            { return token(TokenType.TAN, yytext(), yyline, yycolumn);
            }
          // fall through
          case 119: break;
          case 49:
            { return token(TokenType.BOOL, yytext(), yyline, yycolumn);
            }
          // fall through
          case 120: break;
          case 50:
            { return token(TokenType.COSH, yytext(), yyline, yycolumn);
            }
          // fall through
          case 121: break;
          case 51:
            { return token(TokenType.ELIF, yytext(), yyline, yycolumn);
            }
          // fall through
          case 122: break;
          case 52:
            { return token(TokenType.ELSE, yytext(), yyline, yycolumn);
            }
          // fall through
          case 123: break;
          case 53:
            { return token(TokenType.MEAN, yytext(), yyline, yycolumn);
            }
          // fall through
          case 124: break;
          case 54:
            { return token(TokenType.MODE, yytext(), yyline, yycolumn);
            }
          // fall through
          case 125: break;
          case 55:
            { return token(TokenType.NULL, yytext(), yyline, yycolumn);
            }
          // fall through
          case 126: break;
          case 56:
            { return token(TokenType.SINH, yytext(), yyline, yycolumn);
            }
          // fall through
          case 127: break;
          case 57:
            { return token(TokenType.TANH, yytext(), yyline, yycolumn);
            }
          // fall through
          case 128: break;
          case 58:
            { return token(TokenType.TRUE, yytext(), yyline, yycolumn);
            }
          // fall through
          case 129: break;
          case 59:
            { return token(TokenType.BREAK, yytext(), yyline, yycolumn);
            }
          // fall through
          case 130: break;
          case 60:
            { return token(TokenType.FALSE, yytext(), yyline, yycolumn);
            }
          // fall through
          case 131: break;
          case 61:
            { return token(TokenType.FLOAT, yytext(), yyline, yycolumn);
            }
          // fall through
          case 132: break;
          case 62:
            { return token(TokenType.PRINT, yytext(), yyline, yycolumn);
            }
          // fall through
          case 133: break;
          case 63:
            { return token(TokenType.RACHA, yytext(), yyline, yycolumn);
            }
          // fall through
          case 134: break;
          case 64:
            { return token(TokenType.RANGE, yytext(), yyline, yycolumn);
            }
          // fall through
          case 135: break;
          case 65:
            { return token(TokenType.WHILE, yytext(), yyline, yycolumn);
            }
          // fall through
          case 136: break;
          case 66:
            { return token(TokenType.MEDIAN, yytext(), yyline, yycolumn);
            }
          // fall through
          case 137: break;
          case 67:
            { return token(TokenType.RETURN, yytext(), yyline, yycolumn);
            }
          // fall through
          case 138: break;
          case 68:
            { return token(TokenType.STRING, yytext(), yyline, yycolumn);
            }
          // fall through
          case 139: break;
          case 69:
            { return token(TokenType.EFECTOS, yytext(), yyline, yycolumn);
            }
          // fall through
          case 140: break;
          case 70:
            { return token(TokenType.CONTINUE, yytext(), yyline, yycolumn);
            }
          // fall through
          case 141: break;
          case 71:
            { return token(TokenType.MODELODOSVIAS, yytext(), yyline, yycolumn);
            }
          // fall through
          case 142: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
